# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy your API source code to the container
COPY . .

# Expose the port your API runs on (e.g., 5000)
EXPOSE 5000

# Set environment variables if needed
# ENV NODE_ENV production

# Command to run your API when the container starts
CMD ["npm", "start"]
